" Name:         Night Owl
" Description:  Template for a colorscheme with dark and light variants
" Author:       Klaus-Peter Schreiner <kpschreiner13@gmail.com>
" Maintainer:   Myself <myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Updated: 11.05.2020 16:18:54

" Generated by Colortemplate v2.0.0

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'nightowl'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Define PreProc
hi! link Debug Special
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Number
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Operator PreProc
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StorageClass Type
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  if &background ==# 'dark'
    let g:terminal_ansi_colors = ['#011627', '#ff5874', '#5f7d97', '#ecc48d',
          \ '#5ca7e4', '#2d2c5d', '#7fdbca', '#eeeeee', '#112630', '#f78c6c',
          \ '#addb67', '#fbec9f', '#82aaff', '#c792ea', '#7fdbca', '#d6deeb']
    if get(g:, 'nightowl_transp_bg', 0) && !has('gui_running')
      hi Normal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
      hi Terminal guifg=#d6deeb guibg=NONE guisp=NONE gui=NONE cterm=NONE
    else
      hi Normal guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
      hi Terminal guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    endif
    hi ColorColumn guifg=NONE guibg=#00121e guisp=NONE gui=NONE cterm=NONE
    hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor guifg=#d6deeb guibg=#5f7d97 guisp=NONE gui=NONE cterm=NONE
    hi CursorColumn guifg=fg guibg=#00121e guisp=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#00121e guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=NONE guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi DiffAdd guifg=#d6deeb guibg=#addb67 guisp=NONE gui=reverse cterm=reverse
    hi DiffChange guifg=#d6deeb guibg=#82aaff guisp=NONE gui=reverse cterm=reverse
    hi DiffDelete guifg=#d6deeb guibg=#ff5874 guisp=NONE gui=reverse cterm=reverse
    hi DiffText guifg=#d6deeb guibg=#011627 guisp=NONE gui=bold,reverse cterm=bold,reverse
    hi Directory guifg=#3b546a guibg=#011627 guisp=NONE gui=bold cterm=bold
    hi EndOfBuffer guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi ErrorMsg guifg=#ff5874 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#777777 guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi Folded guifg=#3b546a guibg=#011627 guisp=NONE gui=italic cterm=italic
    hi IncSearch guifg=#3b546a guibg=#d6deeb guisp=NONE gui=standout cterm=standout
    hi LineNr guifg=#3b546a guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi MatchParen guifg=#d6deeb guibg=NONE guisp=NONE gui=underline cterm=underline
    hi ModeMsg guifg=#3b546a guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi MoreMsg guifg=#addb67 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi NonText guifg=#3b546a guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Pmenu guifg=#d6deeb guibg=#0a2a43 guisp=NONE gui=NONE cterm=NONE
    hi PmenuSbar guifg=#d6deeb guibg=#3b546a guisp=NONE gui=NONE cterm=NONE
    hi PmenuSel guifg=#d6deeb guibg=#5f7d97 guisp=NONE gui=NONE cterm=NONE
    hi PmenuThumb guifg=#d6deeb guibg=#112630 guisp=NONE gui=NONE cterm=NONE
    hi Question guifg=#5ca7e4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Search guifg=#d6deeb guibg=#5f7d97 guisp=NONE gui=NONE cterm=NONE
    hi SignColumn guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi SpecialKey guifg=#c792ea guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi SpellBad guifg=#d6deeb guibg=#011627 guisp=#ff5874 gui=NONE cterm=NONE
    hi SpellCap guifg=#d6deeb guibg=#011627 guisp=#82aaff gui=NONE cterm=NONE
    hi SpellLocal guifg=#d6deeb guibg=#011627 guisp=#c792ea gui=NONE cterm=NONE
    hi SpellRare guifg=#d6deeb guibg=#011627 guisp=#7fdbca gui=reverse cterm=reverse
    hi StatusLine guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi StatusLineNC guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi TabLine guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi TabLineFill guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi TabLineSel guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi Title guifg=#d6deeb guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi VertSplit guifg=#5f7d97 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Visual guifg=NONE guibg=#0a2a43 guisp=NONE gui=NONE cterm=NONE
    hi VisualNOS guifg=NONE guibg=#0a2a43 guisp=NONE gui=NONE cterm=NONE
    hi WarningMsg guifg=#82aaff guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi WildMenu guifg=#d6deeb guibg=#5f7d97 guisp=NONE gui=NONE cterm=NONE
    hi Comment guifg=#637777 guibg=NONE guisp=NONE gui=italic cterm=italic
    hi Constant guifg=#addb67 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Error guifg=#ff5874 guibg=#d6deeb guisp=NONE gui=reverse cterm=reverse
    hi Function guifg=#fbec9f guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Identifier guifg=#7fdbca guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Ignore guifg=#d6deeb guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Number guifg=#f78c6c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi PreProc guifg=#c792ea guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Special guifg=#f78c6c guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Statement guifg=#82aaff guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi String guifg=#f4d554 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Todo guifg=#ff5874 guibg=NONE guisp=NONE gui=bold cterm=bold
    hi Type guifg=#addb67 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM guifg=NONE guibg=#d6deeb guisp=NONE gui=NONE cterm=NONE
    hi ToolbarLine guifg=#3b546a guibg=#011627 guisp=NONE gui=NONE cterm=NONE
    hi ToolbarButton guifg=#d6deeb guibg=#5f7d97 guisp=NONE gui=NONE cterm=NONE
    if !s:italics
      hi Folded gui=NONE cterm=NONE
      hi Comment gui=NONE cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  let g:terminal_ansi_colors = ['#403f53', '#de3d3b', '#d3e8f9', '#ecc48d',
        \ '#5ca7e4', '#2d2c5d', '#2aa298', '#fbfbfb', '#112630', '#f78c6c',
        \ '#08916a', '#5f7e97', '#288ed7', '#994cc3', '#2aa298', '#f0f0f0']
  if get(g:, 'nightowl_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#403f53 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#403f53 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor guifg=#fbfbfb guibg=#90a7b2 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#dadada guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#403f53 guibg=#08916a guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#403f53 guibg=#288ed7 guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#403f53 guibg=#de3d3b guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#989fb1 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#de3d3b guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#dadada guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#989fb1 guibg=#fbfbfb guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=#989fb1 guibg=#403f53 guisp=NONE gui=standout cterm=standout
  hi LineNr guifg=#989fb1 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#403f53 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi ModeMsg guifg=#989fb1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#08916a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#989fb1 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#403f53 guibg=#f6f6f6 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#403f53 guibg=#f0f0f0 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#403f53 guibg=#d3e8f9 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#403f53 guibg=#dadada guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#5ca7e4 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#403f53 guibg=#d3e8f9 guisp=NONE gui=NONE cterm=NONE
  hi SignColumn guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#994cc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#403f53 guibg=#fbfbfb guisp=#de3d3b gui=NONE cterm=NONE
  hi SpellCap guifg=#403f53 guibg=#fbfbfb guisp=#288ed7 gui=NONE cterm=NONE
  hi SpellLocal guifg=#403f53 guibg=#fbfbfb guisp=#994cc3 gui=NONE cterm=NONE
  hi SpellRare guifg=#403f53 guibg=#fbfbfb guisp=#2aa298 gui=reverse cterm=reverse
  hi StatusLine guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi TabLine guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#dadada guisp=NONE gui=NONE cterm=NONE
  hi VisualNOS guifg=NONE guibg=#dadada guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#288ed7 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#403f53 guibg=#d3e8f9 guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#989fb1 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#08916a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#de3d3b guibg=#fbfbfb guisp=NONE gui=reverse cterm=reverse
  hi Identifier guifg=#2aa298 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#403f53 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#f78c6c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#994cc3 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#f78c6c guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#288ed7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#de3d3b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Type guifg=#08916a guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=fg guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=#403f53 guibg=#fbfbfb guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#403f53 guibg=#d3e8f9 guisp=NONE gui=NONE cterm=NONE
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if &background ==# 'dark'
    if get(g:, 'nightowl_transp_bg', 0)
      hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=253 ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=253 ctermbg=233 cterm=NONE
      if !has('patch-8.0.0616') " Fix for Vim bug
        set background=dark
      endif
      hi Terminal ctermfg=253 ctermbg=233 cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=233 cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=253 ctermbg=67 cterm=NONE
    hi CursorColumn ctermfg=fg ctermbg=233 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=233 cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=233 cterm=NONE
    hi DiffAdd ctermfg=253 ctermbg=149 cterm=reverse
    hi DiffChange ctermfg=253 ctermbg=111 cterm=reverse
    hi DiffDelete ctermfg=253 ctermbg=204 cterm=reverse
    hi DiffText ctermfg=253 ctermbg=233 cterm=bold,reverse
    hi Directory ctermfg=24 ctermbg=233 cterm=bold
    hi EndOfBuffer ctermfg=253 ctermbg=233 cterm=NONE
    hi ErrorMsg ctermfg=204 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=243 ctermbg=233 cterm=NONE
    hi Folded ctermfg=24 ctermbg=233 cterm=italic
    hi IncSearch ctermfg=24 ctermbg=253 cterm=reverse
    hi LineNr ctermfg=24 ctermbg=233 cterm=NONE
    hi MatchParen ctermfg=253 ctermbg=NONE cterm=underline
    hi ModeMsg ctermfg=24 ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=149 ctermbg=NONE cterm=NONE
    hi NonText ctermfg=24 ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=253 ctermbg=235 cterm=NONE
    hi PmenuSbar ctermfg=253 ctermbg=24 cterm=NONE
    hi PmenuSel ctermfg=253 ctermbg=67 cterm=NONE
    hi PmenuThumb ctermfg=253 ctermbg=235 cterm=NONE
    hi Question ctermfg=39 ctermbg=NONE cterm=NONE
    hi Search ctermfg=253 ctermbg=67 cterm=NONE
    hi SignColumn ctermfg=253 ctermbg=233 cterm=NONE
    hi SpecialKey ctermfg=177 ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=253 ctermbg=233 cterm=NONE
    hi SpellCap ctermfg=253 ctermbg=233 cterm=NONE
    hi SpellLocal ctermfg=253 ctermbg=233 cterm=NONE
    hi SpellRare ctermfg=253 ctermbg=233 cterm=reverse
    hi StatusLine ctermfg=253 ctermbg=233 cterm=NONE
    hi StatusLineNC ctermfg=253 ctermbg=233 cterm=NONE
    hi TabLine ctermfg=253 ctermbg=233 cterm=NONE
    hi TabLineFill ctermfg=253 ctermbg=233 cterm=NONE
    hi TabLineSel ctermfg=253 ctermbg=233 cterm=NONE
    hi Title ctermfg=253 ctermbg=233 cterm=NONE
    hi VertSplit ctermfg=67 ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=235 cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=235 cterm=NONE
    hi WarningMsg ctermfg=111 ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=253 ctermbg=67 cterm=NONE
    hi Comment ctermfg=66 ctermbg=NONE cterm=italic
    hi Constant ctermfg=149 ctermbg=NONE cterm=NONE
    hi Error ctermfg=204 ctermbg=253 cterm=reverse
    hi Function ctermfg=229 ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=116 ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=253 ctermbg=NONE cterm=NONE
    hi Number ctermfg=209 ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=177 ctermbg=NONE cterm=NONE
    hi Special ctermfg=209 ctermbg=NONE cterm=NONE
    hi Statement ctermfg=111 ctermbg=NONE cterm=NONE
    hi String ctermfg=221 ctermbg=NONE cterm=NONE
    hi Todo ctermfg=204 ctermbg=NONE cterm=bold
    hi Type ctermfg=149 ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=NONE ctermbg=253 cterm=NONE
    hi ToolbarLine ctermfg=24 ctermbg=233 cterm=NONE
    hi ToolbarButton ctermfg=253 ctermbg=67 cterm=NONE
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'nightowl_transp_bg', 0) && !has('gui_running')
    hi Normal ctermfg=238 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=238 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=238 ctermbg=231 cterm=NONE
    hi Terminal ctermfg=238 ctermbg=231 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=231 ctermbg=109 cterm=NONE
  hi CursorColumn ctermfg=238 ctermbg=231 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=253 ctermbg=231 cterm=NONE
  hi DiffAdd ctermfg=238 ctermbg=29 cterm=reverse
  hi DiffChange ctermfg=238 ctermbg=32 cterm=reverse
  hi DiffDelete ctermfg=238 ctermbg=167 cterm=reverse
  hi DiffText ctermfg=238 ctermbg=231 cterm=bold,reverse
  hi Directory ctermfg=247 ctermbg=231 cterm=NONE
  hi EndOfBuffer ctermfg=238 ctermbg=231 cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=231 cterm=NONE
  hi FoldColumn ctermfg=253 ctermbg=231 cterm=NONE
  hi Folded ctermfg=247 ctermbg=231 cterm=italic
  hi IncSearch ctermfg=247 ctermbg=238 cterm=reverse
  hi LineNr ctermfg=247 ctermbg=231 cterm=NONE
  hi MatchParen ctermfg=238 ctermbg=NONE cterm=underline
  hi ModeMsg ctermfg=247 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=29 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=247 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=238 ctermbg=255 cterm=NONE
  hi PmenuSbar ctermfg=238 ctermbg=255 cterm=NONE
  hi PmenuSel ctermfg=238 ctermbg=153 cterm=NONE
  hi PmenuThumb ctermfg=238 ctermbg=253 cterm=NONE
  hi Question ctermfg=39 ctermbg=NONE cterm=NONE
  hi Search ctermfg=238 ctermbg=153 cterm=NONE
  hi SignColumn ctermfg=238 ctermbg=231 cterm=NONE
  hi SpecialKey ctermfg=98 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=238 ctermbg=231 cterm=NONE
  hi SpellCap ctermfg=238 ctermbg=231 cterm=NONE
  hi SpellLocal ctermfg=238 ctermbg=231 cterm=NONE
  hi SpellRare ctermfg=238 ctermbg=231 cterm=reverse
  hi StatusLine ctermfg=238 ctermbg=231 cterm=NONE
  hi StatusLineNC ctermfg=238 ctermbg=231 cterm=NONE
  hi TabLine ctermfg=238 ctermbg=231 cterm=NONE
  hi TabLineFill ctermfg=238 ctermbg=231 cterm=NONE
  hi TabLineSel ctermfg=238 ctermbg=231 cterm=NONE
  hi Title ctermfg=238 ctermbg=231 cterm=NONE
  hi VertSplit ctermfg=238 ctermbg=231 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=253 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=253 cterm=NONE
  hi WarningMsg ctermfg=32 ctermbg=231 cterm=NONE
  hi WildMenu ctermfg=238 ctermbg=153 cterm=NONE
  hi Comment ctermfg=247 ctermbg=NONE cterm=italic
  hi Constant ctermfg=29 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=231 cterm=reverse
  hi Identifier ctermfg=37 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=238 ctermbg=NONE cterm=NONE
  hi Number ctermfg=209 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=98 ctermbg=NONE cterm=NONE
  hi Special ctermfg=209 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=32 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=167 ctermbg=NONE cterm=bold
  hi Type ctermfg=29 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=238 ctermbg=231 cterm=NONE
  hi ToolbarButton ctermfg=238 ctermbg=153 cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if &background ==# 'dark'
    if get(g:, 'nightowl_transp_bg', 0)
      hi Normal ctermfg=NONE ctermbg=NONE cterm=NONE
      hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
    else
      hi Normal ctermfg=White ctermbg=Black cterm=NONE
      hi Terminal ctermfg=White ctermbg=Black cterm=NONE
    endif
    hi ColorColumn ctermfg=NONE ctermbg=Gray cterm=NONE
    hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
    hi Cursor ctermfg=White ctermbg=LightBlue cterm=NONE
    hi CursorColumn ctermfg=fg ctermbg=Gray cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=Gray cterm=NONE
    hi CursorLineNr ctermfg=NONE ctermbg=Black cterm=NONE
    hi DiffAdd ctermfg=White ctermbg=LightGreen cterm=reverse
    hi DiffChange ctermfg=White ctermbg=LightBlue cterm=reverse
    hi DiffDelete ctermfg=White ctermbg=Red cterm=reverse
    hi DiffText ctermfg=White ctermbg=Black cterm=bold,reverse
    hi Directory ctermfg=LightGray ctermbg=Black cterm=bold
    hi EndOfBuffer ctermfg=White ctermbg=Black cterm=NONE
    hi ErrorMsg ctermfg=Red ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=DarkGray ctermbg=Black cterm=NONE
    hi Folded ctermfg=LightGray ctermbg=Black cterm=italic
    hi IncSearch ctermfg=LightGray ctermbg=White cterm=reverse
    hi LineNr ctermfg=LightGray ctermbg=Black cterm=NONE
    hi MatchParen ctermfg=White ctermbg=NONE cterm=underline
    hi ModeMsg ctermfg=LightGray ctermbg=NONE cterm=NONE
    hi MoreMsg ctermfg=LightGreen ctermbg=NONE cterm=NONE
    hi NonText ctermfg=LightGray ctermbg=NONE cterm=NONE
    hi Pmenu ctermfg=White ctermbg=Gray cterm=NONE
    hi PmenuSbar ctermfg=White ctermbg=LightGray cterm=NONE
    hi PmenuSel ctermfg=White ctermbg=LightBlue cterm=NONE
    hi PmenuThumb ctermfg=White ctermbg=DarkGrey cterm=NONE
    hi Question ctermfg=Blue ctermbg=NONE cterm=NONE
    hi Search ctermfg=White ctermbg=LightBlue cterm=NONE
    hi SignColumn ctermfg=White ctermbg=Black cterm=NONE
    hi SpecialKey ctermfg=LightMagenta ctermbg=NONE cterm=NONE
    hi SpellBad ctermfg=White ctermbg=Black cterm=NONE
    hi SpellCap ctermfg=White ctermbg=Black cterm=NONE
    hi SpellLocal ctermfg=White ctermbg=Black cterm=NONE
    hi SpellRare ctermfg=White ctermbg=Black cterm=reverse
    hi StatusLine ctermfg=White ctermbg=Black cterm=NONE
    hi StatusLineNC ctermfg=White ctermbg=Black cterm=NONE
    hi TabLine ctermfg=White ctermbg=Black cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Black cterm=NONE
    hi Title ctermfg=White ctermbg=Black cterm=NONE
    hi VertSplit ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi Visual ctermfg=NONE ctermbg=Gray cterm=NONE
    hi VisualNOS ctermfg=NONE ctermbg=Gray cterm=NONE
    hi WarningMsg ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi WildMenu ctermfg=White ctermbg=LightBlue cterm=NONE
    hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
    hi Constant ctermfg=LightGreen ctermbg=NONE cterm=NONE
    hi Error ctermfg=Red ctermbg=White cterm=reverse
    hi Function ctermfg=LightYellow ctermbg=NONE cterm=NONE
    hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
    hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
    hi Number ctermfg=DarkYellow ctermbg=NONE cterm=NONE
    hi PreProc ctermfg=LightMagenta ctermbg=NONE cterm=NONE
    hi Special ctermfg=DarkYellow ctermbg=NONE cterm=NONE
    hi Statement ctermfg=LightBlue ctermbg=NONE cterm=NONE
    hi String ctermfg=Yellow ctermbg=NONE cterm=NONE
    hi Todo ctermfg=Red ctermbg=NONE cterm=bold
    hi Type ctermfg=LightGreen ctermbg=NONE cterm=NONE
    hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
    hi ToolbarLine ctermfg=LightGray ctermbg=Black cterm=NONE
    hi ToolbarButton ctermfg=White ctermbg=LightBlue cterm=NONE
    if !s:italics
      hi Folded cterm=NONE
      hi Comment cterm=NONE
    endif
    unlet s:t_Co s:italics
    finish
  endif
  " Light background
  if get(g:, 'nightowl_transp_bg', 0) && !has('gui_running')
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi Terminal ctermfg=Black ctermbg=White cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=LightGray cterm=NONE
  hi Conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=Gray cterm=NONE
  hi CursorColumn ctermfg=Black ctermbg=White cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=LightGray cterm=NONE
  hi CursorLineNr ctermfg=DarkGray ctermbg=White cterm=NONE
  hi DiffAdd ctermfg=Black ctermbg=LightGreen cterm=reverse
  hi DiffChange ctermfg=Black ctermbg=LightBlue cterm=reverse
  hi DiffDelete ctermfg=Black ctermbg=Red cterm=reverse
  hi DiffText ctermfg=Black ctermbg=White cterm=bold,reverse
  hi Directory ctermfg=Gray ctermbg=White cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=White cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=White cterm=NONE
  hi FoldColumn ctermfg=DarkGray ctermbg=White cterm=NONE
  hi Folded ctermfg=Gray ctermbg=White cterm=italic
  hi IncSearch ctermfg=Gray ctermbg=Black cterm=reverse
  hi LineNr ctermfg=Gray ctermbg=White cterm=NONE
  hi MatchParen ctermfg=Black ctermbg=NONE cterm=underline
  hi ModeMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=Gray cterm=NONE
  hi PmenuSbar ctermfg=Black ctermbg=LightGray cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=DarkGray cterm=NONE
  hi Question ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Search ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi SignColumn ctermfg=Black ctermbg=White cterm=NONE
  hi SpecialKey ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Black ctermbg=White cterm=NONE
  hi SpellCap ctermfg=Black ctermbg=White cterm=NONE
  hi SpellLocal ctermfg=Black ctermbg=White cterm=NONE
  hi SpellRare ctermfg=Black ctermbg=White cterm=reverse
  hi StatusLine ctermfg=Black ctermbg=White cterm=NONE
  hi StatusLineNC ctermfg=Black ctermbg=White cterm=NONE
  hi TabLine ctermfg=Black ctermbg=White cterm=NONE
  hi TabLineFill ctermfg=Black ctermbg=White cterm=NONE
  hi TabLineSel ctermfg=Black ctermbg=White cterm=NONE
  hi Title ctermfg=Black ctermbg=White cterm=NONE
  hi VertSplit ctermfg=Black ctermbg=White cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi WarningMsg ctermfg=LightBlue ctermbg=White cterm=NONE
  hi WildMenu ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
  hi Constant ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=White cterm=reverse
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
  hi Number ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Statement ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Red ctermbg=NONE cterm=bold
  hi Type ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=Black ctermbg=White cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=DarkCyan cterm=NONE
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: white                #d6deeb                ~        White
" Color: bright               #eeeeee                ~        LightGray
" Color: dark                 #011627                ~        Black
" Color: neardark             #112630                ~        DarkGrey
" Color: deepdark             #00121e                ~        Gray
" Color: purple               #c792ea                ~        LightMagenta
" Color: green                #addb67                ~        LightGreen
" Color: yellow               #ecc48d                ~        LightYellow
" Color: gray                 #637777                ~        Gray
" Color: blue                 #82aaff                ~        LightBlue
" Color: yellow2              #f78c6c                ~        DarkYellow
" Color: yellow3              #fbec9f                ~        LightYellow
" Color: yellow4              #f4d554                ~        Yellow
" Color: green2               #7fdbca                ~        Cyan
" Color: red                  #ff5874                ~        Red
" Color: blue2                #5ca7e4                ~        Blue
" Color: gray1                #111111                ~        Black
" Color: gray2                #222222                ~        Black
" Color: gray3                #333333                ~        Gray
" Color: gray4                #444444                ~        Gray
" Color: gray7                #777777                ~        DarkGray
" Color: gray8                #3b546a                ~        LightGray
" Color: graya                #aaaaaa                ~        LightGray
" Color: purple2              #2d2c5d                ~        DarkMagenta
" Color: hoki                 #5f7d97                ~        LightBlue
" Color: grayblue             #0a2a43                ~        Gray
" Term colors: dark red hoki yellow blue2 purple2 green2 bright
" Term colors: neardark yellow2 green yellow3
" Term colors: blue purple green2 white
" Background: light
" Color: white                #f0f0f0                ~        LightGray
" Color: bright               #fbfbfb                ~        White
" Color: dark                 #403f53                ~        Black
" Color: neardark             #112630                ~        DarkGrey
" Color: deepdark             #00121e                ~        Gray
" Color: purple               #994cc3                ~        LightMagenta
" Color: green                #08916a                ~        LightGreen
" Color: yellow               #ecc48d                ~        LightYellow
" Color: gray                 #989fb1                ~        Gray
" Color: blue                 #288ed7                ~        LightBlue
" Color: yellow2              #f78c6c                ~        DarkYellow
" Color: yellow3              #5f7e97                ~        LightYellow
" Color: yellow4              #c96765                ~        Yellow
" Color: green2               #2aa298                ~        Cyan
" Color: red                  #de3d3b                ~        Red
" Color: blue2                #5ca7e4                ~        Blue
" Color: gray1                #111111                ~        Black
" Color: gray2                #222222                ~        Black
" Color: gray3                #333333                ~        Gray
" Color: gray4                #f6f6f6                ~        Gray
" Color: gray7                #dadada                ~        DarkGray
" Color: gray8                #f0f0f0                ~        LightGray
" Color: graya                #aaaaaa                ~        LightGray
" Color: purple2              #2d2c5d                ~        DarkMagenta
" Color: hoki                 #d3e8f9                ~        DarkCyan
" Color: graygreen            #90a7b2                ~        Gray
" Term colors: dark red hoki yellow blue2 purple2 green2 bright
" Term colors: neardark yellow2 green yellow3
" Term colors: blue purple green2 white
" Background: any
" vim: et ts=2 sw=2
